### ISSUE TITLE
I got this error from install

### ISSUE THREAD

**Issue by fingerblaster** [zzhaolei/transient-prompt.fish#7] opened 2023-03-28 14:07 UTC
`fisher install version 4.4.3
Fetching https://api.github.com/repos/zzhaolei/transient.fish/tarball/HEAD
Installing zzhaolei/transient.fish
           /home/test/.config/fish/functions/__fish_mode_prompt.fish
           /home/test/.config/fish/functions/__fish_prompt.fish
           /home/test/.config/fish/functions/__fish_right_prompt.fish
           /home/test/.config/fish/functions/__transient.fish
           /home/test/.config/fish/conf.d/transient.fish
Installed 1 plugin/s
test: Missing argument at index 3
0 =
    ^
- (line 23):
    if test $__fish_prompt_status_generation = $transient_status_generation
       ^
in function '__transient_fish_prompt'
        called on line 22 of file ~/.config/fish/conf.d/transient.fish
in function 'fish_prompt'
in command substitution
`

**Comment by zzhaolei** [comment] 2023-03-30 02:52
~~Sorry, I can't reproduce this problem. Can you try to manually delete these files and reinstall them?~~
```
/home/test/.config/fish/functions/__fish_mode_prompt.fish
/home/test/.config/fish/functions/__fish_prompt.fish
/home/test/.config/fish/functions/__fish_right_prompt.fish
/home/test/.config/fish/functions/__transient.fish
/home/test/.config/fish/conf.d/transient.fish
```

edit: I think this is a problem in .config/fish/functions/fish_prompt.fish, the plugin has been installed successfully ("Installed 1 plugin"), but when the fish_prompt function is executed, an exception occurs.

**Comment by zzhaolei** [comment] 2023-03-30 03:16
Now I will close this issue.

**Closed as completed by zzhaolei** 2023-03-30 03:16 UTC
